### ISSUE TITLE
gmlgo: add rh to apply logo/etc to EXE

### ISSUE THREAD

**Issue by silbinarywolf** [silbinarywolf/gml-go#111]
Got the idea from OpenDiablo2
https://github.com/OpenDiablo2/OpenDiablo2/blob/f81eb5764d48b662d3e3064694fb3f3fdcfa71c6/.travis.yml#L21

```yml
language: go
os:
  - linux
  - osx
  - windows
go:
  - 1.13.3
addons:
  apt:
    packages:
      - libx11-dev
      - mesa-common-dev
      - libglfw3-dev
      - libgles2-mesa-dev
      - libasound2-dev
script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install 7zip.portable ; fi
  - mkdir -p ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - go get
  - go build -ldflags "-X main.GitCommit=$TRAVIS_COMMIT -X main.GitBranch=$TRAVIS_TAG"
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./rh.exe -open OpenDiablo2.exe -save OpenDiablo2.exe -action addskip -res d2logo.ico -mask ICONGROUP,MAIN, ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cp ./OpenDiablo2.exe ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME ; else cp ./OpenDiablo2 ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME; fi
  - cp ./d2logo.png ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - cp ./config.json ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 7z a -r opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME ; else tar -cvzf opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz ./opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME ; fi
git:
  quiet: true
  depth: 1
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: "$GithubApi"
  file_glob: true
  file: opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.*
  skip_cleanup: true
  overwrite: true
  name: "OpenDiablo Unstable (Build $TRAVIS_BUILD_NUMBER)"
  prerelease: true
  on:
    tags: true
```
